### ISSUE TITLE
謝辞

### ISSUE THREAD

**Issue by teramotodaiki** [yurkth/sprator#2]
ブログ記事から日本人の方だろうと推察して、日本語で書きます。
ある方のツイートで、大変かわいらしいアイコンに思わず目を奪われてしまい、リンクを辿っているうちにこちらの実装にたどり着きました。MIT ライセンスだったので、勝手ながら当方で TypeScript による再実装を行い、Node.js で動作する簡単なウェブサーバを実装しました
（ちなみに、PR #1 はその時に間違えて送ってしまったものです。ご容赦願います）

https://github.com/hackforplay/sprator

これを作った背景としては、[弊社のウェブサービス](https://hackforplay.xyz/) でユーザー向けの自動生成アイコンを提供しようと思っていたのですが、例えば GitHub などに使われているアイコン(5x5 ドット）は全然かわいくないので、なにか参考になるアイコンの生成方法はないものかと考えていたのです。ちょうど弊社ではドット絵をよく使っていることもあり、こちらの Sprator はまさに最高の生成アルゴリズムでした。また、アルゴリズムについて詳細まで説明されていたブログ記事にもかなり助けられました。深く感謝申し上げます

何らかの形でお礼が出来たらと思っているのですが、当方はライセンスをいただきたいのではなく、このまま OSS と続けていただけることが一番望ましいと思っておりますので、もし差し支えなければ、ウェブサービス上のどこかに @yurkth  様のハンドルネームを表示させていただけないでしょうか？
具体的には、[ライセンス表記のページ](https://www.hackforplay.xyz/pages/agreement/software-license)に載せさせていただく形です。ぜひ、ご検討ください 🙏

**Comment by yurkth** [comment]
ご連絡ありがとうございます。
もともと自分用に作ったプログラムでしたが、お役に立てて何よりです。Spratorにつきましては今後もOSSとしてMITライセンスで公開していく予定です。

ライセンス表記のご提案もありがとうございます。ご提案の通り、ライセンス表記のページにハンドルネームを記載していただきたいと思います。可能であればGitHubのリポジトリへのリンクもお願いしたいです。
よろしくお願いいたします。

**Comment by teramotodaiki** [comment]
@yurkth ありがとうございます！ライセンス表記についても、承知しました。こちらの Issue は Close しておきます
